version: "3.9"
services:
  spotihook:
    image: ghcr.io/shuaiscott/spotihook
    container_name: spotihook
    restart: always
    volumes:
      - ./spotihook.db:/usr/src/app/spotihook.db
    environment:
      - CLIENT_ID=<CLIENT_ID>
      - CLIENT_SECRET=<CLIENT_SECRET>
      - PLAYLIST_ID=<PLAYLIST_ID>
      - WEBHOOK_URL_TEMPLATE=<WEBHOOK_URL_TEMPLATE>
      - WEBHOOK_METHOD=POST
      - WEBHOOK_CONTENT_TYPE=JSON
      # OPTIONAL: - WEBHOOK_BODY_TEMPLATE=<WEBHOOK_BODY_TEMPLATE>
      - DELAY_AMOUNT=10
      - DELAY_UNIT=SECONDS
      - DEBUG=False
